package com.threeoa.bigdata.web.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-04-10T18:28:37.165+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://webservice.web.bigdata.threeoa.com/", name = "viewQueryDetail")
@XmlSeeAlso({ObjectFactory.class})
public interface ViewQueryDetail {

    @WebMethod
    @RequestWrapper(localName = "getClassScheduleForClassroom", targetNamespace = "http://webservice.web.bigdata.threeoa.com/", className = "com.threeoa.bigdata.web.webservice.GetClassScheduleForClassroom")
    @ResponseWrapper(localName = "getClassScheduleForClassroomResponse", targetNamespace = "http://webservice.web.bigdata.threeoa.com/", className = "com.threeoa.bigdata.web.webservice.GetClassScheduleForClassroomResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getClassScheduleForClassroom(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        java.lang.String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        java.lang.String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        int arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        int arg9
    );

    @WebMethod
    @RequestWrapper(localName = "getClassScheduleForStudentNonPaged", targetNamespace = "http://webservice.web.bigdata.threeoa.com/", className = "com.threeoa.bigdata.web.webservice.GetClassScheduleForStudentNonPaged")
    @ResponseWrapper(localName = "getClassScheduleForStudentNonPagedResponse", targetNamespace = "http://webservice.web.bigdata.threeoa.com/", className = "com.threeoa.bigdata.web.webservice.GetClassScheduleForStudentNonPagedResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getClassScheduleForStudentNonPaged(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        java.lang.String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        java.lang.String arg7
    );

    @WebMethod
    @RequestWrapper(localName = "getLessonInfo", targetNamespace = "http://webservice.web.bigdata.threeoa.com/", className = "com.threeoa.bigdata.web.webservice.GetLessonInfo")
    @ResponseWrapper(localName = "getLessonInfoResponse", targetNamespace = "http://webservice.web.bigdata.threeoa.com/", className = "com.threeoa.bigdata.web.webservice.GetLessonInfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getLessonInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.Long arg3
    );

    @WebMethod
    @RequestWrapper(localName = "getCurrentWeekClassScheduleByStudentWristbandId", targetNamespace = "http://webservice.web.bigdata.threeoa.com/", className = "com.threeoa.bigdata.web.webservice.GetCurrentWeekClassScheduleByStudentWristbandId")
    @ResponseWrapper(localName = "getCurrentWeekClassScheduleByStudentWristbandIdResponse", targetNamespace = "http://webservice.web.bigdata.threeoa.com/", className = "com.threeoa.bigdata.web.webservice.GetCurrentWeekClassScheduleByStudentWristbandIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getCurrentWeekClassScheduleByStudentWristbandId(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebMethod
    @RequestWrapper(localName = "getClassScheduleForTeacherNonPaged", targetNamespace = "http://webservice.web.bigdata.threeoa.com/", className = "com.threeoa.bigdata.web.webservice.GetClassScheduleForTeacherNonPaged")
    @ResponseWrapper(localName = "getClassScheduleForTeacherNonPagedResponse", targetNamespace = "http://webservice.web.bigdata.threeoa.com/", className = "com.threeoa.bigdata.web.webservice.GetClassScheduleForTeacherNonPagedResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getClassScheduleForTeacherNonPaged(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        java.lang.String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        java.lang.String arg7
    );

    @WebMethod
    @RequestWrapper(localName = "getClassScheduleForStudentNonPagedByStudentWristbandId", targetNamespace = "http://webservice.web.bigdata.threeoa.com/", className = "com.threeoa.bigdata.web.webservice.GetClassScheduleForStudentNonPagedByStudentWristbandId")
    @ResponseWrapper(localName = "getClassScheduleForStudentNonPagedByStudentWristbandIdResponse", targetNamespace = "http://webservice.web.bigdata.threeoa.com/", className = "com.threeoa.bigdata.web.webservice.GetClassScheduleForStudentNonPagedByStudentWristbandIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getClassScheduleForStudentNonPagedByStudentWristbandId(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        java.lang.String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        java.lang.String arg7
    );

    @WebMethod
    @RequestWrapper(localName = "getClassSchedule", targetNamespace = "http://webservice.web.bigdata.threeoa.com/", className = "com.threeoa.bigdata.web.webservice.GetClassSchedule")
    @ResponseWrapper(localName = "getClassScheduleResponse", targetNamespace = "http://webservice.web.bigdata.threeoa.com/", className = "com.threeoa.bigdata.web.webservice.GetClassScheduleResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getClassSchedule(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        java.lang.String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        int arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        int arg8
    );

    @WebMethod
    @RequestWrapper(localName = "getCurrentWeekClassScheduleByClassroom", targetNamespace = "http://webservice.web.bigdata.threeoa.com/", className = "com.threeoa.bigdata.web.webservice.GetCurrentWeekClassScheduleByClassroom")
    @ResponseWrapper(localName = "getCurrentWeekClassScheduleByClassroomResponse", targetNamespace = "http://webservice.web.bigdata.threeoa.com/", className = "com.threeoa.bigdata.web.webservice.GetCurrentWeekClassScheduleByClassroomResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getCurrentWeekClassScheduleByClassroom(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebMethod
    @RequestWrapper(localName = "getClassScheduleForStudent", targetNamespace = "http://webservice.web.bigdata.threeoa.com/", className = "com.threeoa.bigdata.web.webservice.GetClassScheduleForStudent")
    @ResponseWrapper(localName = "getClassScheduleForStudentResponse", targetNamespace = "http://webservice.web.bigdata.threeoa.com/", className = "com.threeoa.bigdata.web.webservice.GetClassScheduleForStudentResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getClassScheduleForStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        java.lang.String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        java.lang.String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        int arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        int arg9
    );

    @WebMethod
    @RequestWrapper(localName = "init", targetNamespace = "http://webservice.web.bigdata.threeoa.com/", className = "com.threeoa.bigdata.web.webservice.Init")
    @ResponseWrapper(localName = "initResponse", targetNamespace = "http://webservice.web.bigdata.threeoa.com/", className = "com.threeoa.bigdata.web.webservice.InitResponse")
    public void init();

    @WebMethod
    @RequestWrapper(localName = "getClassScheduleForTeacher", targetNamespace = "http://webservice.web.bigdata.threeoa.com/", className = "com.threeoa.bigdata.web.webservice.GetClassScheduleForTeacher")
    @ResponseWrapper(localName = "getClassScheduleForTeacherResponse", targetNamespace = "http://webservice.web.bigdata.threeoa.com/", className = "com.threeoa.bigdata.web.webservice.GetClassScheduleForTeacherResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getClassScheduleForTeacher(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        java.lang.String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        java.lang.String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        int arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        int arg9
    );

    @WebMethod
    @RequestWrapper(localName = "getClassScheduleForTeacherNonPagedByWristbandId", targetNamespace = "http://webservice.web.bigdata.threeoa.com/", className = "com.threeoa.bigdata.web.webservice.GetClassScheduleForTeacherNonPagedByWristbandId")
    @ResponseWrapper(localName = "getClassScheduleForTeacherNonPagedByWristbandIdResponse", targetNamespace = "http://webservice.web.bigdata.threeoa.com/", className = "com.threeoa.bigdata.web.webservice.GetClassScheduleForTeacherNonPagedByWristbandIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getClassScheduleForTeacherNonPagedByWristbandId(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        java.lang.String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        java.lang.String arg7
    );

    @WebMethod
    @RequestWrapper(localName = "getClassScheduleForClassroomNonPaged", targetNamespace = "http://webservice.web.bigdata.threeoa.com/", className = "com.threeoa.bigdata.web.webservice.GetClassScheduleForClassroomNonPaged")
    @ResponseWrapper(localName = "getClassScheduleForClassroomNonPagedResponse", targetNamespace = "http://webservice.web.bigdata.threeoa.com/", className = "com.threeoa.bigdata.web.webservice.GetClassScheduleForClassroomNonPagedResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getClassScheduleForClassroomNonPaged(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        java.lang.String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        java.lang.String arg7
    );

    @WebMethod
    @RequestWrapper(localName = "getCurrentWeekClassScheduleByTeacher", targetNamespace = "http://webservice.web.bigdata.threeoa.com/", className = "com.threeoa.bigdata.web.webservice.GetCurrentWeekClassScheduleByTeacher")
    @ResponseWrapper(localName = "getCurrentWeekClassScheduleByTeacherResponse", targetNamespace = "http://webservice.web.bigdata.threeoa.com/", className = "com.threeoa.bigdata.web.webservice.GetCurrentWeekClassScheduleByTeacherResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getCurrentWeekClassScheduleByTeacher(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebMethod
    @RequestWrapper(localName = "getDataByView", targetNamespace = "http://webservice.web.bigdata.threeoa.com/", className = "com.threeoa.bigdata.web.webservice.GetDataByView")
    @ResponseWrapper(localName = "getDataByViewResponse", targetNamespace = "http://webservice.web.bigdata.threeoa.com/", className = "com.threeoa.bigdata.web.webservice.GetDataByViewResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getDataByView(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getCurrentWeekClassScheduleByStudent", targetNamespace = "http://webservice.web.bigdata.threeoa.com/", className = "com.threeoa.bigdata.web.webservice.GetCurrentWeekClassScheduleByStudent")
    @ResponseWrapper(localName = "getCurrentWeekClassScheduleByStudentResponse", targetNamespace = "http://webservice.web.bigdata.threeoa.com/", className = "com.threeoa.bigdata.web.webservice.GetCurrentWeekClassScheduleByStudentResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getCurrentWeekClassScheduleByStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebMethod
    @RequestWrapper(localName = "getCurrentWeekClassScheduleByTeacherWristbandId", targetNamespace = "http://webservice.web.bigdata.threeoa.com/", className = "com.threeoa.bigdata.web.webservice.GetCurrentWeekClassScheduleByTeacherWristbandId")
    @ResponseWrapper(localName = "getCurrentWeekClassScheduleByTeacherWristbandIdResponse", targetNamespace = "http://webservice.web.bigdata.threeoa.com/", className = "com.threeoa.bigdata.web.webservice.GetCurrentWeekClassScheduleByTeacherWristbandIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getCurrentWeekClassScheduleByTeacherWristbandId(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );
}
