package com.threeoa.bigdata.web.webservice;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.2.4 2018-04-10T18:28:37.278+08:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "viewQueryDetailWS", wsdlLocation = "file:./viewQueryDetailWS.xml", targetNamespace = "http://webservice.web.bigdata.threeoa.com/")
public class ViewQueryDetailWS extends Service {

	public final static URL WSDL_LOCATION;

	public final static QName SERVICE = new QName("http://webservice.web.bigdata.threeoa.com/", "viewQueryDetailWS");
	public final static QName ViewQueryDetailPort = new QName("http://webservice.web.bigdata.threeoa.com/",
			"viewQueryDetailPort");
	static {
		URL url = null;
		try {

			url = new URL("file:./viewQueryDetailWS.xml");

		} catch (MalformedURLException e) {
			java.util.logging.Logger.getLogger(ViewQueryDetailWS.class.getName()).log(java.util.logging.Level.INFO,
					"Can not initialize the default wsdl from {0}", "file:./viewQueryDetailWS.xml");
		}
		WSDL_LOCATION = url;
	}

	public ViewQueryDetailWS(URL wsdlLocation) {
		super(wsdlLocation, SERVICE);
	}

	public ViewQueryDetailWS(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ViewQueryDetailWS() {
		super(WSDL_LOCATION, SERVICE);
	}

	public ViewQueryDetailWS(WebServiceFeature... features) {
		super(WSDL_LOCATION, SERVICE, features);
	}

	public ViewQueryDetailWS(URL wsdlLocation, WebServiceFeature... features) {
		super(wsdlLocation, SERVICE, features);
	}

	public ViewQueryDetailWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
		super(wsdlLocation, serviceName, features);
	}

	/**
	 *
	 * @return returns ViewQueryDetail
	 */
	@WebEndpoint(name = "viewQueryDetailPort")
	public ViewQueryDetail getViewQueryDetailPort() {
		return super.getPort(ViewQueryDetailPort, ViewQueryDetail.class);
	}

	/**
	 *
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns ViewQueryDetail
	 */
	@WebEndpoint(name = "viewQueryDetailPort")
	public ViewQueryDetail getViewQueryDetailPort(WebServiceFeature... features) {
		return super.getPort(ViewQueryDetailPort, ViewQueryDetail.class, features);
	}

}
